[package]
name = "aoc2018"
version = "0.1.0"
authors = ["Glowpelt <glowpelt@chakat.space>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
nom = {version = "4.1", features = ["verbose-errors"]}
nalgebra = "0.16.0"
typenum = "1.10"
chrono = {version = "0.4"}
